name: txdx3_client
description: "TxDx3 - Open source, self-hosted personal productivity"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.2
  flutter_hooks:
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  pocketbase: ^0.17.0
  shared_preferences: ^2.2.2
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  custom_lint:
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true
