name: txdx3_client
description: "TxDx3 - Open source, self-hosted personal productivity"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.6
  clock: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_data: ^1.5.15
  hooks_riverpod: ^2.4.9
  path_provider: ^2.0.11
  shared_preferences: ^2.2.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  custom_lint: ^0.6.0
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.0
  mockito: ^5.4.4
  test: ^1.24.9

flutter:
  uses-material-design: true
